package dev.sixik.generator_accelerator.api.config;

import ca.spottedleaf.yamlconfig.annotation.Adaptable;
import ca.spottedleaf.yamlconfig.annotation.Serializable;

@Adaptable
public final class GAConfig {

    @Adaptable
    public static final class DfcDebugConfig {

        @Serializable(
                comment = """
                        Enables runtime spline statistics collection.
                        Mirrors old VM arg: -Ddfc.codegen.splineRuntimeStats=true
                        """
        )
        public boolean splineRuntimeStats = false;

        @Serializable(
                comment = """
                        Sampling shift for spline runtime stats.
                        Lower values sample more often.
                        Mirrors old VM arg: -Ddfc.codegen.splineRuntimeStats.sampleShift=8
                        """
        )
        public int splineRuntimeStatsSampleShift = 8;

        @Serializable(
                comment = """
                        Emits spline runtime hooks into generated bytecode.
                        Mirrors old VM arg: -Ddfc.codegen.splineRuntimeStats.emit=true
                        """
        )
        public boolean splineRuntimeStatsEmit = true;

        @Serializable(
                comment = """
                        Enables LUT-guided spline segment selection.
                        Mirrors old VM arg: -Ddfc.codegen.splineSegmentLut=true
                        """
        )
        public boolean splineSegmentLut = false;

        @Serializable(
                comment = """
                        Minimum spline size before LUT mode is considered.
                        Mirrors old VM arg: -Ddfc.codegen.splineSegmentLutMinPoints=9
                        """
        )
        public int splineSegmentLutMinPoints = 9;

        @Serializable(
                comment = """
                        Bucket count for spline LUT generation.
                        Mirrors old VM arg: -Ddfc.codegen.splineSegmentLutBuckets=128
                        """
        )
        public int splineSegmentLutBuckets = 128;

        @Serializable(
                comment = """
                        Spline search mode: auto, linear, or binary.
                        Mirrors old VM arg: -Ddfc.codegen.splineSearchMode=auto
                        """
        )
        public String splineSearchMode = "auto";

        @Serializable(
                comment = """
                        Maximum spline point count that still uses linear search in auto mode.
                        Default is 3 so 4-point splines use exact binary search.
                        Mirrors old VM arg: -Ddfc.codegen.splineLinearSearchMaxPoints=3
                        """
        )
        public int splineLinearSearchMaxPoints = 3;

        @Serializable(
                comment = """
                        Enables cell-fill runtime statistics.
                        Mirrors old VM arg: -Ddfc.cellfill.stats=true
                        """
        )
        public boolean cellFillStats = false;

        @Serializable(
                comment = """
                        Enables extra residual class debug for cell-fill stats.
                        Mirrors old VM arg: -Ddfc.cellfill.stats.residualClassDebug=true
                        """
        )
        public boolean cellFillResidualClassDebug = false;

        @Serializable(
                comment = """
                        Enables cell-fill parity checks.
                        Mirrors old VM arg: -Ddfc.cellfill.parity=true
                        """
        )
        public boolean cellFillParity = false;

        @Serializable(
                comment = """
                        Maximum number of cell-fill parity checks.
                        Mirrors old VM arg: -Ddfc.cellfill.parity.maxChecks=1024
                        """
        )
        public int cellFillParityMaxChecks = 1024;

        @Serializable(
                comment = """
                        Allowed epsilon for cell-fill parity checks.
                        Mirrors old VM arg: -Ddfc.cellfill.parity.epsilon=1.0E-9
                        """
        )
        public double cellFillParityEpsilon = 1.0E-9;

        @Serializable(
                comment = """
                        Enables direct-read cache fast-path statistics.
                        Mirrors old VM arg: -Dga.dfc.cacheFastPath.stats=true
                        """
        )
        public boolean cacheFastPathStats = false;

        @Serializable(
                comment = """
                        Logs additional spline-search debug information.
                        Mirrors old VM arg: -Ddfc.codegen.logSplineSearch=true
                        """
        )
        public boolean logSplineSearch = false;

        @Serializable(
                comment = """
                        Minimum node count for cell-lattice hoist candidates.
                        Mirrors old VM arg: -Ddfc.codegen.latticeMinHoistSize=5
                        """
        )
        public int latticeMinHoistSize = 5;

        @Serializable(
                comment = """
                        Allows compilation of marker inners in the compiling visitor.
                        Mirrors old VM arg: -Ddfc.compileMarkerInners=true
                        """
        )
        public boolean compileMarkerInners = false;

        @Serializable(
                comment = """
                        Enables direct residual extern cell-fill specialization.
                        Mirrors old VM arg: -Ddfc.codegen.cellFillDirectExternResidual=true
                        """
        )
        public boolean cellFillDirectExternResidual = false;

        @Serializable(
                comment = """
                        Enables add-extern cell-fill override experiments.
                        Mirrors old VM arg: -Ddfc.codegen.cellFillAddExternOverride=true
                        """
        )
        public boolean cellFillAddExternOverride = false;

        @Serializable(
                comment = """
                        Enables warming of raw density_function registry entries.
                        Mirrors old VM arg: -Ddfc.warmer.rawDensityFunctions=true
                        """
        )
        public boolean warmerRawDensityFunctions = false;

        @Serializable(
                comment = """
                        Maximum warmed noise settings count. Use -1 for unlimited.
                        Mirrors old VM arg: -Ddfc.warmer.maxSettings=...
                        """
        )
        public int warmerMaxSettings = -1;

        @Serializable(
                comment = """
                        Maximum warmed raw density functions count. Use -1 for unlimited.
                        Mirrors old VM arg: -Ddfc.warmer.maxDensityFunctions=...
                        """
        )
        public int warmerMaxDensityFunctions = -1;
    }

    @Serializable(
            comment = """
                    Do not change, used internally.
                    """
    )
    public int version = 2;

    @Serializable(
            comment = """
                    Density Function Compiler debug and tuning options.
                    These values are applied to the old DFC system properties on startup,
                    so you no longer need to manage most DFC VM args manually.
                    """
    )
    public DfcDebugConfig dfc = new DfcDebugConfig();

    // @generatedMixinConfigFields:start

    @Serializable(
            comment = """
                    Enables the Density Function Compiler mixin module.
                    Also disables conflicting C2ME DFC mixins when their compat classes are present.
                    """
    )
    public boolean enableDensityCompilerPatch = true;

    @Serializable(
            comment = """
                    Enables optimization for "ImprovedNoise, perlinNoise, SimplexNoise"
                    """
    )
    public boolean enableNoisePath = true;

    @Serializable(
            comment = """
                    Example toggle generated from @MixinOnConfig.
                    Enable it to allow ExampleGeneratedToggleMixin to load.
                    """
    )
    public boolean enableBasicExampleMixinTest = false;

    @Serializable(
            comment = """
                    Generated mixin toggle for dev.sixik.generator_accelerator.common.basic.mixin.ExampleCompatMixin.
                    """
    )
    public boolean enableExampleCompatMixin = true;

    // @generatedMixinConfigFields:end
}
