package dev.sixik.generator_accelerator.api.config;

import ca.spottedleaf.yamlconfig.annotation.Adaptable;
import ca.spottedleaf.yamlconfig.annotation.Serializable;

@Adaptable
public final class GAConfig {

    @Adaptable
    public static final class BiomeClimateConfig {

        @Serializable(
                comment = """
                        Enables second warm-start lookup for climate index searches.
                        Mirrors old VM arg: -Dga.climate.secondWarmStart=true
                        """
        )
        public boolean secondWarmStart = true;

        @Serializable(
                comment = """
                        Enables nearest-first child sorting during climate index traversal.
                        Mirrors old VM arg: -Dga.climate.sortChildrenByDistance=true
                        """
        )
        public boolean sortChildrenByDistance = true;

        @Serializable(
                comment = """
                        Enables adaptive disabling of useless query cache instances.
                        Mirrors old VM arg: -Dga.climate.adaptiveQueryCache=true
                        """
        )
        public boolean adaptiveQueryCache = true;

        @Serializable(
                comment = """
                        Query cache size for biome climate lookups.
                        Use 0 to disable. Non-power-of-two values are rounded down internally.
                        Mirrors old VM arg: -Dga.climate.queryCacheSize=64
                        """
        )
        public int queryCacheSize = 64;

        @Serializable(
                comment = """
                        Probe count before adaptive cache disable is evaluated.
                        Mirrors old VM arg: -Dga.climate.queryCacheDisableProbes=2048
                        """
        )
        public int queryCacheDisableProbes = 2048;

        @Serializable(
                comment = """
                        Hit-rate shift used by adaptive cache heuristics.
                        Mirrors old VM arg: -Dga.climate.queryCacheDisableHitRateShift=7
                        """
        )
        public int queryCacheDisableHitRateShift = 7;

        @Serializable(
                comment = """
                        Leaf-count threshold for switching to linear search.
                        0 keeps the tree path always enabled.
                        Mirrors old VM arg: -Dga.climate.linearSearchThreshold=0
                        """
        )
        public int linearSearchThreshold = 0;
    }

    @Adaptable
    public static final class DfcDebugConfig {

        @Serializable(
                comment = """
                        Enables runtime spline statistics collection.
                        Mirrors old VM arg: -Ddfc.codegen.splineRuntimeStats=true
                        """
        )
        public boolean splineRuntimeStats = false;

        @Serializable(
                comment = """
                        Sampling shift for spline runtime stats.
                        Lower values sample more often.
                        Mirrors old VM arg: -Ddfc.codegen.splineRuntimeStats.sampleShift=8
                        """
        )
        public int splineRuntimeStatsSampleShift = 8;

        @Serializable(
                comment = """
                        Emits spline runtime hooks into generated bytecode.
                        Mirrors old VM arg: -Ddfc.codegen.splineRuntimeStats.emit=true
                        """
        )
        public boolean splineRuntimeStatsEmit = true;

        @Serializable(
                comment = """
                        Enables LUT-guided spline segment selection.
                        Mirrors old VM arg: -Ddfc.codegen.splineSegmentLut=true
                        """
        )
        public boolean splineSegmentLut = false;

        @Serializable(
                comment = """
                        Minimum spline size before LUT mode is considered.
                        Mirrors old VM arg: -Ddfc.codegen.splineSegmentLutMinPoints=9
                        """
        )
        public int splineSegmentLutMinPoints = 9;

        @Serializable(
                comment = """
                        Bucket count for spline LUT generation.
                        Mirrors old VM arg: -Ddfc.codegen.splineSegmentLutBuckets=128
                        """
        )
        public int splineSegmentLutBuckets = 128;

        @Serializable(
                comment = """
                        Spline search mode: auto, linear, or binary.
                        Mirrors old VM arg: -Ddfc.codegen.splineSearchMode=auto
                        """
        )
        public String splineSearchMode = "auto";

        @Serializable(
                comment = """
                        Maximum spline point count that still uses linear search in auto mode.
                        Default is 3 so 4-point splines use exact binary search.
                        Mirrors old VM arg: -Ddfc.codegen.splineLinearSearchMaxPoints=3
                        """
        )
        public int splineLinearSearchMaxPoints = 3;

        @Serializable(
                comment = """
                        Enables cell-fill runtime statistics.
                        Mirrors old VM arg: -Ddfc.cellfill.stats=true
                        """
        )
        public boolean cellFillStats = false;

        @Serializable(
                comment = """
                        Enables extra residual class debug for cell-fill stats.
                        Mirrors old VM arg: -Ddfc.cellfill.stats.residualClassDebug=true
                        """
        )
        public boolean cellFillResidualClassDebug = false;

        @Serializable(
                comment = """
                        Enables cell-fill parity checks.
                        Mirrors old VM arg: -Ddfc.cellfill.parity=true
                        """
        )
        public boolean cellFillParity = false;

        @Serializable(
                comment = """
                        Maximum number of cell-fill parity checks.
                        Mirrors old VM arg: -Ddfc.cellfill.parity.maxChecks=1024
                        """
        )
        public int cellFillParityMaxChecks = 1024;

        @Serializable(
                comment = """
                        Allowed epsilon for cell-fill parity checks.
                        Mirrors old VM arg: -Ddfc.cellfill.parity.epsilon=1.0E-9
                        """
        )
        public double cellFillParityEpsilon = 1.0E-9;

        @Serializable(
                comment = """
                        Enables direct-read cache fast-path statistics.
                        Mirrors old VM arg: -Dga.dfc.cacheFastPath.stats=true
                        """
        )
        public boolean cacheFastPathStats = false;

        @Serializable(
                comment = """
                        Maximum tracked spline runtime classes in debug statistics.
                        Mirrors old VM arg: -Dga.dfc.splineStats.maxTrackedClasses=256
                        """
        )
        public int splineStatsMaxTrackedClasses = 256;

        @Serializable(
                comment = """
                        Maximum tracked cell-fill classes in debug statistics.
                        Mirrors old VM arg: -Dga.dfc.cellFillStats.maxTrackedClasses=256
                        """
        )
        public int cellFillStatsMaxTrackedClasses = 256;

        @Serializable(
                comment = """
                        Maximum compiled-class registry entries kept alive.
                        Mirrors old VM arg: -Dga.dfc.registry.maxEntries=4096
                        """
        )
        public int registryMaxEntries = 4096;

        @Serializable(
                comment = """
                        Logs additional spline-search debug information.
                        Mirrors old VM arg: -Ddfc.codegen.logSplineSearch=true
                        """
        )
        public boolean logSplineSearch = false;

        @Serializable(
                comment = """
                        Minimum node count for cell-lattice hoist candidates.
                        Mirrors old VM arg: -Ddfc.codegen.latticeMinHoistSize=5
                        """
        )
        public int latticeMinHoistSize = 5;

        @Serializable(
                comment = """
                        Allows compilation of marker inners in the compiling visitor.
                        Mirrors old VM arg: -Ddfc.compileMarkerInners=true
                        """
        )
        public boolean compileMarkerInners = false;

        @Serializable(
                comment = """
                        Enables direct residual extern cell-fill specialization.
                        Mirrors old VM arg: -Ddfc.codegen.cellFillDirectExternResidual=true
                        """
        )
        public boolean cellFillDirectExternResidual = false;

        @Serializable(
                comment = """
                        Enables add-extern cell-fill override experiments.
                        Mirrors old VM arg: -Ddfc.codegen.cellFillAddExternOverride=true
                        """
        )
        public boolean cellFillAddExternOverride = false;

        @Serializable(
                comment = """
                        Enables warming of raw density_function registry entries.
                        Mirrors old VM arg: -Ddfc.warmer.rawDensityFunctions=true
                        """
        )
        public boolean warmerRawDensityFunctions = false;

        @Serializable(
                comment = """
                        Maximum warmed noise settings count. Use -1 for unlimited.
                        Mirrors old VM arg: -Ddfc.warmer.maxSettings=...
                        """
        )
        public int warmerMaxSettings = -1;

        @Serializable(
                comment = """
                        Maximum warmed raw density functions count. Use -1 for unlimited.
                        Mirrors old VM arg: -Ddfc.warmer.maxDensityFunctions=...
                        """
        )
        public int warmerMaxDensityFunctions = -1;
    }

    @Serializable(
            comment = """
                    Do not change, used internally.
                    """
    )
    public int version = 3;

    @Serializable(
            comment = """
                    Enables optimization for "ImprovedNoise, perlinNoise, SimplexNoise"
                    """
    )
    public boolean enableNoisePath = true;

    @Serializable
    public boolean enableBiomePath = true;

    @Serializable(
            comment = """
                    Biome climate index tuning options.
                    These values are applied to the old biome system properties on startup,
                    so you no longer need to manage biome VM args manually.
                    """
    )
    public BiomeClimateConfig biomeClimate = new BiomeClimateConfig();

    @Serializable(
            comment = """
                    Density Function Compiler debug and tuning options.
                    These values are applied to the old DFC system properties on startup,
                    so you no longer need to manage DFC VM args manually.
                    """
    )
    public DfcDebugConfig dfc = new DfcDebugConfig();

    // @generatedMixinConfigFields:start

    @Serializable(
            comment = """
                    Example toggle generated from @MixinOnConfig.
                    Enable it to allow ExampleGeneratedToggleMixin to load.
                    """
    )
    public boolean enableBasicExampleMixinTest = false;

    @Serializable(
            comment = """
                    Enables the Density Function Compiler mixin module.
                    Also disables conflicting C2ME DFC mixins when their compat classes are present.
                    """
    )
    public boolean enableDensityCompilerPatch = true;

    @Serializable(
            comment = """
                    Generated mixin toggle for dev.sixik.generator_accelerator.common.basic.mixin.ExampleCompatMixin.
                    """
    )
    public boolean enableExampleCompatMixin = true;

    @Serializable(
            comment = """
                    TerraBlender rebuilds a full uniqueness Area for every biome chunk.
                    The Area is already locked and deterministic, so sharing the cloned source's existing
                    Area avoids large per-chunk array allocation. Restore vanilla TerraBlender behaviour with
                    If `false` a pack depends on per-chunk caches.
                    """
    )
    public boolean terraBlenderRecreateUniquenessPerChunk = true;

    // @generatedMixinConfigFields:end
}
