package dev.sixik.generator_accelerator.api.config;

import ca.spottedleaf.yamlconfig.annotation.Adaptable;
import ca.spottedleaf.yamlconfig.annotation.Serializable;

@Adaptable
public final class GAConfig {

    @Adaptable
    public static final class BiomeClimateConfig {

        @Serializable(
                comment = """
                        Enables second warm-start lookup for climate index searches.
                        Mirrors old VM arg: -Dga.climate.secondWarmStart=true
                        """
        )
        public boolean secondWarmStart = true;

        @Serializable(
                comment = """
                        Enables nearest-first child sorting during climate index traversal.
                        Mirrors old VM arg: -Dga.climate.sortChildrenByDistance=true
                        """
        )
        public boolean sortChildrenByDistance = true;

        @Serializable(
                comment = """
                        Enables adaptive disabling of useless query cache instances.
                        Mirrors old VM arg: -Dga.climate.adaptiveQueryCache=true
                        """
        )
        public boolean adaptiveQueryCache = true;

        @Serializable(
                comment = """
                        Query cache size for biome climate lookups.
                        Use 0 to disable. Non-power-of-two values are rounded down internally.
                        Mirrors old VM arg: -Dga.climate.queryCacheSize=64
                        """
        )
        public int queryCacheSize = 64;

        @Serializable(
                comment = """
                        Probe count before adaptive cache disable is evaluated.
                        Mirrors old VM arg: -Dga.climate.queryCacheDisableProbes=2048
                        """
        )
        public int queryCacheDisableProbes = 2048;

        @Serializable(
                comment = """
                        Hit-rate shift used by adaptive cache heuristics.
                        Mirrors old VM arg: -Dga.climate.queryCacheDisableHitRateShift=7
                        """
        )
        public int queryCacheDisableHitRateShift = 7;

        @Serializable(
                comment = """
                        Leaf-count threshold for switching to linear search.
                        0 keeps the tree path always enabled.
                        Mirrors old VM arg: -Dga.climate.linearSearchThreshold=0
                        """
        )
        public int linearSearchThreshold = 0;
    }

    @Adaptable
    public static final class DfcDebugConfig {

        @Serializable(
                comment = """
                        Enables runtime spline statistics collection.
                        Mirrors old VM arg: -Ddfc.codegen.splineRuntimeStats=true
                        """
        )
        public boolean splineRuntimeStats = false;

        @Serializable(
                comment = """
                        Sampling shift for spline runtime stats.
                        Lower values sample more often.
                        Mirrors old VM arg: -Ddfc.codegen.splineRuntimeStats.sampleShift=8
                        """
        )
        public int splineRuntimeStatsSampleShift = 8;

        @Serializable(
                comment = """
                        Emits spline runtime hooks into generated bytecode.
                        Mirrors old VM arg: -Ddfc.codegen.splineRuntimeStats.emit=true
                        """
        )
        public boolean splineRuntimeStatsEmit = true;

        @Serializable(
                comment = """
                        Enables LUT-guided spline segment selection.
                        Mirrors old VM arg: -Ddfc.codegen.splineSegmentLut=true
                        """
        )
        public boolean splineSegmentLut = false;

        @Serializable(
                comment = """
                        Minimum spline size before LUT mode is considered.
                        Mirrors old VM arg: -Ddfc.codegen.splineSegmentLutMinPoints=9
                        """
        )
        public int splineSegmentLutMinPoints = 9;

        @Serializable(
                comment = """
                        Bucket count for spline LUT generation.
                        Mirrors old VM arg: -Ddfc.codegen.splineSegmentLutBuckets=128
                        """
        )
        public int splineSegmentLutBuckets = 128;

        @Serializable(
                comment = """
                        Spline search mode: auto, linear, or binary.
                        Mirrors old VM arg: -Ddfc.codegen.splineSearchMode=auto
                        """
        )
        public String splineSearchMode = "auto";

        @Serializable(
                comment = """
                        Maximum spline point count that still uses linear search in auto mode.
                        Default is 3 so 4-point splines use exact binary search.
                        Mirrors old VM arg: -Ddfc.codegen.splineLinearSearchMaxPoints=3
                        """
        )
        public int splineLinearSearchMaxPoints = 3;

        @Serializable(
                comment = """
                        Enables cell-fill runtime statistics.
                        Mirrors old VM arg: -Ddfc.cellfill.stats=true
                        """
        )
        public boolean cellFillStats = false;

        @Serializable(
                comment = """
                        Enables Beardifier runtime statistics collection.
                        Keep false for normal world loading; this is diagnostic-only.
                        Mirrors old VM arg: -Dga.beardifier.stats=true
                        """
        )
        public boolean beardifierStats = false;

        @Serializable(
                comment = """
                        Enables NoiseChunk fillSlice/selectCellYZ timing statistics.
                        Keep false for normal world loading; this is diagnostic-only.
                        Mirrors old VM arg: -Dga.noiseChunk.timingStats=true
                        """
        )
        public boolean noiseChunkTimingStats = false;

        @Serializable(
                comment = """
                        Enables extra residual class debug for cell-fill stats.
                        Mirrors old VM arg: -Ddfc.cellfill.stats.residualClassDebug=true
                        """
        )
        public boolean cellFillResidualClassDebug = false;

        @Serializable(
                comment = """
                        Enables cell-fill parity checks.
                        Mirrors old VM arg: -Ddfc.cellfill.parity=true
                        """
        )
        public boolean cellFillParity = false;

        @Serializable(
                comment = """
                        Maximum number of cell-fill parity checks.
                        Mirrors old VM arg: -Ddfc.cellfill.parity.maxChecks=1024
                        """
        )
        public int cellFillParityMaxChecks = 1024;

        @Serializable(
                comment = """
                        Allowed epsilon for cell-fill parity checks.
                        Mirrors old VM arg: -Ddfc.cellfill.parity.epsilon=1.0E-9
                        """
        )
        public double cellFillParityEpsilon = 1.0E-9;

        @Serializable(
                comment = """
                        Enables direct-read cache fast-path statistics.
                        Mirrors old VM arg: -Dga.dfc.cacheFastPath.stats=true
                        """
        )
        public boolean cacheFastPathStats = false;

        @Serializable(
                comment = """
                        Maximum tracked spline runtime classes in debug statistics.
                        Mirrors old VM arg: -Dga.dfc.splineStats.maxTrackedClasses=256
                        """
        )
        public int splineStatsMaxTrackedClasses = 256;

        @Serializable(
                comment = """
                        Maximum tracked cell-fill classes in debug statistics.
                        Mirrors old VM arg: -Dga.dfc.cellFillStats.maxTrackedClasses=256
                        """
        )
        public int cellFillStatsMaxTrackedClasses = 256;

        @Serializable(
                comment = """
                        Maximum compiled-class registry entries kept alive.
                        Mirrors old VM arg: -Dga.dfc.registry.maxEntries=4096
                        """
        )
        public int registryMaxEntries = 4096;

        @Serializable(
                comment = """
                        Logs additional spline-search debug information.
                        Mirrors old VM arg: -Ddfc.codegen.logSplineSearch=true
                        """
        )
        public boolean logSplineSearch = false;

        @Serializable(
                comment = """
                        Minimum node count for cell-lattice hoist candidates.
                        Mirrors old VM arg: -Ddfc.codegen.latticeMinHoistSize=5
                        """
        )
        public int latticeMinHoistSize = 5;

        @Serializable(
                comment = """
                        Allows compilation of marker inners in the compiling visitor.
                        Mirrors old VM arg: -Ddfc.compileMarkerInners=true
                        """
        )
        public boolean compileMarkerInners = false;

        @Serializable(
                comment = """
                        Allows per-NoiseChunk CacheAllInCell filler lazy compilation.
                        This is experimental and can create many chunk-specific compiled classes.
                        Keep false for normal world loading.
                        Mirrors old VM arg: -Dga.dfc.lazyCellCacheCompile=true
                        """
        )
        public boolean lazyCellCacheCompile = false;

        @Serializable(
                comment = """
                        Maximum per-lifecycle lazy CacheAllInCell filler compiles when lazyCellCacheCompile is enabled.
                        Mirrors old VM arg: -Dga.dfc.lazyCellCacheCompile.max=128
                        """
        )
        public int lazyCellCacheCompileMax = 128;

        @Serializable(
                comment = """
                        Allows a small lifecycle budget of lazy compilation for NoiseInterpolator roots used by fillSlice.
                        Only active together with fillSliceGpuPrototype; CPU-only slice filling is faster without it.
                        Mirrors old VM arg: -Dga.dfc.fillSliceLazyCompile=true
                        """
        )
        public boolean fillSliceLazyCompile = true;

        @Serializable(
                comment = """
                        Maximum per-lifecycle lazy fillSlice root compiles when fillSliceLazyCompile is enabled.
                        Mirrors old VM arg: -Dga.dfc.fillSliceLazyCompile.max=16
                        """
        )
        public int fillSliceLazyCompileMax = 16;

        @Serializable(
                comment = """
                        Allows the first fillSlice GPU prototype to batch one compiled NoiseInterpolator root over a whole slice plane.
                        This is a correctness experiment; failed, skipped, or parity-failing launches fall back to the existing CPU path.
                        Mirrors old VM arg: -Dga.dfc.gpu.fillSlicePrototype=true
                        """
        )
        public boolean fillSliceGpuPrototype = false;

        @Serializable(
                comment = """
                        Allows compiled cell-fill roots to try the GPU payload runtime before falling back to CPU.
                        Disabled by default: current 128-point cell batches rarely form useful microbatches.
                        Mirrors old VM arg: -Dga.dfc.gpu.cellFillPrototype=false
                        """
        )
        public boolean gpuCellFillPrototype = false;

        @Serializable(
                comment = """
                        Maximum RandomState instances that may eagerly compile their NoiseRouter per server lifecycle.
                        Use 0 to disable eager DFC router compilation, or -1 to restore the old unlimited behaviour.
                        This prevents world-load stalls when a modpack constructs many RandomState instances.
                        Mirrors old VM arg: -Dga.dfc.randomStateCompile.max=0
                        """
        )
        public int randomStateCompileMax = 0;

        @Serializable(
                comment = """
                        Comma-separated NoiseRouter root names compiled for admitted RandomStates.
                        Use all for the old full-router behavior, or e.g. finalDensity for a narrow GPU/runtime probe.
                        Mirrors old VM arg: -Dga.dfc.randomStateCompile.routerRoots=all
                        """
        )
        public String randomStateCompileRouterRoots = "all";

        @Serializable(
                comment = """
                        Allows eager Climate.Sampler compilation for RandomStates admitted by randomStateCompileMax.
                        Disabling this keeps biome sampling vanilla while preserving router compilation.
                        Mirrors old VM arg: -Dga.dfc.randomStateCompile.sampler=true
                        """
        )
        public boolean randomStateCompileSampler = true;

        @Serializable(
                comment = """
                        Maximum real worldgen GPU payload batches per lifecycle.
                        Use 0 to keep runtime GPU batches disabled while allowing GPU Probe diagnostics; -1 means unlimited.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeBatchMax=0
                        """
        )
        public int gpuRuntimeBatchMax = 0;

        @Serializable(
                comment = """
                        Minimum point count for real worldgen GPU runtime batches.
                        Single 128-point NoiseChunk cell batches are too small; microbatching may pass when the padded launch reaches this threshold.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeMinPoints=1024
                        """
        )
        public int gpuRuntimeMinPoints = 1024;

        @Serializable(
                comment = """
                        Maximum same-shape DFC cell requests packed into one prepared JavaToGpu runtime launch.
                        Use 1 to disable runtime microbatch packing while keeping opportunistic lock behavior.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeMicroBatchMax=8
                        """
        )
        public int gpuRuntimeMicroBatchMax = 8;

        @Serializable(
                comment = """
                        Minimum collected runtime microbatch size required before launching GPU.
                        Smaller groups fall back to CPU to avoid expensive 128-point single GPU launches.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeMicroBatchMin=2
                        """
        )
        public int gpuRuntimeMicroBatchMin = 2;

        @Serializable(
                comment = """
                        Maximum nanoseconds the GPU lock owner spins to collect compatible runtime microbatch requests.
                        Keep this small; 100000ns is 0.1ms.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeMicroBatchCollectNanos=100000
                        """
        )
        public long gpuRuntimeMicroBatchCollectNanos = 100_000L;

        @Serializable(
                comment = """
                        Maximum nanoseconds a busy caller waits for a microbatch leader to accept it before CPU fallback.
                        Default 0 keeps busy callers purely opportunistic; accepted callers still wait for GPU completion.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeMicroBatchWaitNanos=0
                        """
        )
        public long gpuRuntimeMicroBatchWaitNanos = 0L;

        @Serializable(
                comment = """
                        Consecutive single-request microbatch candidates before runtime GPU enters temporary backoff.
                        This avoids repeatedly taking the runtime lock when the current workload is not batching.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeMicroBatchBackoffSingleStreak=1
                        """
        )
        public int gpuRuntimeMicroBatchBackoffSingleStreak = 1;

        @Serializable(
                comment = """
                        Consecutive busy GPU runtime attempts before runtime GPU enters temporary backoff.
                        This avoids paying repeated queue/lock overhead when another worker owns the serialized runtime.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeMicroBatchBackoffBusyStreak=32
                        """
        )
        public int gpuRuntimeMicroBatchBackoffBusyStreak = 32;

        @Serializable(
                comment = """
                        Runtime batch checks skipped after microbatch backoff triggers.
                        Keep this short for fillSlice prototype sampling; after this window, GPU is sampled again.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeMicroBatchBackoffBatches=64
                        """
        )
        public int gpuRuntimeMicroBatchBackoffBatches = 64;

        @Serializable(
                comment = """
                        Maximum runtime GPU payload batches checked against CPU during real worldgen.
                        Use 0 to disable runtime GPU parity after preflight; this should stay small for performance runs.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeParityBatches=8
                        """
        )
        public int gpuRuntimeParityBatches = 8;

        @Serializable(
                comment = """
                        Makes real worldgen GPU batches opportunistic: if another chunk worker is using the GPU runtime,
                        the caller falls back to CPU instead of waiting on the serialized runtime lock.
                        Mirrors old VM arg: -Dga.dfc.gpu.opportunisticRuntimeLock=true
                        """
        )
        public boolean gpuRuntimeOpportunisticLock = true;

        @Serializable(
                comment = """
                        Maximum nanoseconds a direct runtime GPU caller waits for the serialized runtime lock before CPU fallback.
                        Use 0 for immediate opportunistic fallback; positive values can increase worker-thread stalls.
                        Mirrors old VM arg: -Dga.dfc.gpu.runtimeLockWaitNanos=0
                        """
        )
        public long gpuRuntimeLockWaitNanos = 0L;

        @Serializable(
                comment = """
                        Calls the generated JavaToGpu launcher directly instead of the generic launcher invoker.
                        This is a runtime-overhead experiment; disable if direct generated launcher lookup fails.
                        Mirrors old VM arg: -Dga.dfc.gpu.directGeneratedLauncher=true
                        """
        )
        public boolean gpuDirectGeneratedLauncher = true;

        @Serializable(
                comment = """
                        Enables direct residual extern cell-fill specialization.
                        Mirrors old VM arg: -Ddfc.codegen.cellFillDirectExternResidual=true
                        """
        )
        public boolean cellFillDirectExternResidual = false;

        @Serializable(
                comment = """
                        Enables add-extern cell-fill override experiments.
                        Mirrors old VM arg: -Ddfc.codegen.cellFillAddExternOverride=true
                        """
        )
        public boolean cellFillAddExternOverride = false;

        @Serializable(
                comment = """
                        Enables the narrow ADD(Beardifier, residual) cell-fill override experiment.
                        Unlike cellFillAddExternOverride, this does not specialize generic ADD(extern, residual) roots.
                        Mirrors old VM arg: -Ddfc.codegen.cellFillAddBeardifierOverride=true
                        """
        )
        public boolean cellFillAddBeardifierOverride = false;

        @Serializable(
                comment = """
                        Enables the direct-interpolator scalar marker cell-fill override for compact marker-only roots.
                        Disabled by default until the specialized path proves stable across worldgen runs.
                        Mirrors old VM arg: -Ddfc.codegen.cellFillScalarMarkerOverride=true
                        """
        )
        public boolean cellFillScalarMarkerOverride = false;

        @Serializable(
                comment = """
                        Enables warming of wired noise_settings RandomStates during server start.
                        This can be expensive in large modpacks, so it is opt-in only.
                        Mirrors old VM arg: -Ddfc.warmer.noiseSettings=true
                        """
        )
        public boolean warmerNoiseSettings = false;

        @Serializable(
                comment = """
                        Enables warming of raw density_function registry entries.
                        Mirrors old VM arg: -Ddfc.warmer.rawDensityFunctions=true
                        """
        )
        public boolean warmerRawDensityFunctions = false;

        @Serializable(
                comment = """
                        Maximum warmed noise settings count. Use -1 for unlimited.
                        Default 0 avoids compiling every registered noise_settings entry during server start.
                        Mirrors old VM arg: -Ddfc.warmer.maxSettings=...
                        """
        )
        public int warmerMaxSettings = 0;

        @Serializable(
                comment = """
                        Maximum warmed raw density functions count. Use -1 for unlimited.
                        Mirrors old VM arg: -Ddfc.warmer.maxDensityFunctions=...
                        """
        )
        public int warmerMaxDensityFunctions = -1;
    }

    @Serializable(
            comment = """
                    Do not change, used internally.
                    """
    )
    public int version = 12;

    @Serializable(
            comment = """
                    Enables optimization for "ImprovedNoise, perlinNoise, SimplexNoise"
                    """
    )
    public boolean enableNoisePath = true;

    @Serializable
    public boolean enableBiomePath = true;

    @Serializable(
            comment = """
                    Biome climate index tuning options.
                    These values are applied to the old biome system properties on startup,
                    so you no longer need to manage biome VM args manually.
                    """
    )
    public BiomeClimateConfig biomeClimate = new BiomeClimateConfig();

    @Serializable(
            comment = """
                    Density Function Compiler debug and tuning options.
                    These values are applied to the old DFC system properties on startup,
                    so you no longer need to manage DFC VM args manually.
                    """
    )
    public DfcDebugConfig dfc = new DfcDebugConfig();

    // @generatedMixinConfigFields:start

    @Serializable(
            comment = """
                    Example toggle generated from @MixinOnConfig.
                    Enable it to allow ExampleGeneratedToggleMixin to load.
                    """
    )
    public boolean enableBasicExampleMixinTest = false;

    @Serializable(
            comment = """
                    Enables the Density Function Compiler mixin module.
                    Also disables conflicting C2ME DFC mixins when their compat classes are present.
                    """
    )
    public boolean enableDensityCompilerPatch = true;

    @Serializable(
            comment = """
                    Generated mixin toggle for dev.sixik.generator_accelerator.common.basic.mixin.ExampleCompatMixin.
                    """
    )
    public boolean enableExampleCompatMixin = true;

    @Serializable(
            comment = """
                    TerraBlender rebuilds a full uniqueness Area for every biome chunk.
                    The Area is already locked and deterministic, so sharing the cloned source's existing
                    Area avoids large per-chunk array allocation. Restore vanilla TerraBlender behaviour with
                    If `false` a pack depends on per-chunk caches.
                    """
    )
    public boolean terraBlenderRecreateUniquenessPerChunk = true;

    // @generatedMixinConfigFields:end
}
