package dev.sixik.generator_accelerator.common.worldgen.profile;

public enum WorldgenEffectFlag {
    PURE,
    READS_BLOCKS,
    READS_BIOMES,
    READS_HEIGHTMAP,
    READS_STRUCTURES,
    WRITES_BLOCKS,
    WRITES_HEIGHTMAP,
    WRITES_POSTPROCESSING,
    WRITES_SCHEDULED_TICKS,
    CROSS_CHUNK_READ,
    CROSS_CHUNK_WRITE,
    USES_RANDOM,
    USES_GLOBAL_MUTABLE_STATE,
    USES_REFLECTION,
    USES_NATIVE,
    USES_IO,
    USES_THREADS,
    USES_SYNCHRONIZED,
    CALLS_UNKNOWN_METHOD,
    ALLOC_HEAVY,
    STREAM_HEAVY,
    ORDER_SENSITIVE
}
