package dev.sixik.generator_accelerator.common.density.compiler.compiler.noise;

import net.minecraft.world.level.levelgen.synth.ImprovedNoise;
import net.minecraft.world.level.levelgen.synth.NormalNoise;

/**
 * Snapshot of every per-instance constant that
 * {@link NormalNoise#getValue(double, double, double)} pulls out of its {@code first}
 * and {@code second} {@link net.minecraft.world.level.levelgen.synth.PerlinNoise}
 * branches. The compiler reads this once at compile-time, bakes the doubles into
 * {@code LDC} instructions, and emits the active-octave loop fully unrolled — so the
 * generated bytecode no longer carries any of the {@code d1 *= 2.0; d2 /= 2.0} stepping
 * arithmetic, the null-check on {@code noiseLevels[i]}, or the
 * {@code amplitudes.getDouble(i)} virtual fastutil dispatch that vanilla pays per call.
 *
 * <p>Each octave's contribution to the final sample is
 * {@code amp_i * ImprovedNoise.noise(wrap(x*freqInput_i), wrap(y*freqInput_i), wrap(z*freqInput_i)) * freqValue_i}.
 * We pre-multiply {@code amp_i * freqValue_i} into a single
 * {@link PerlinSpec#ampValueFactors ampValueFactors[]} entry so the per-octave
 * post-multiplication collapses to one DMUL.
 *
 * <p>"Active" means {@code noiseLevels[i] != null} (which in practice also means
 * {@code amplitudes[i] != 0.0} — vanilla's {@code PerlinNoise} constructor only
 * allocates an {@link ImprovedNoise} for non-zero amplitudes). We strip the inactive
 * entries during {@link NoiseSpecCache#specFor specFor} so the bytecode never has to
 * branch around them, but the {@code 2^i / 0.5^i} factors are computed against the
 * <em>original</em> octave index, matching vanilla's unconditional in-loop stepping.
 */
public record NoiseSpec(
        /** {@link NormalNoise#getValueFactor()}. Multiplied once after summing first+second. */
        double valueFactor,
        /** First {@link net.minecraft.world.level.levelgen.synth.PerlinNoise} branch. Coords used as-is. */
        PerlinSpec first,
        /**
         * Second branch. Vanilla scales each input coordinate by
         * {@link #INPUT_FACTOR} before invoking second.getValue, so
         * {@link PerlinSpec#inputCoordScale} is {@link #INPUT_FACTOR} here (and
         * {@code 1.0} on {@code first}). The pre-scale is done once in the codegen
         * and stored in a fresh local slot before the per-octave loop runs.
         */
        PerlinSpec second
) {
    /**
     * The hard-coded {@code NormalNoise.INPUT_FACTOR} that scales the second branch's
     * input coordinates. Mirrors {@link NormalNoise} {@code private static final
     * double INPUT_FACTOR = 1.0181268882175227}.
     */
    public static final double INPUT_FACTOR = 1.0181268882175227;

    /**
     * Per-{@link net.minecraft.world.level.levelgen.synth.PerlinNoise} flattened
     * representation. All four arrays are parallel and length-equal to
     * {@link #activeOctaves activeOctaves.length}.
     */
    public record PerlinSpec(
            /** Surviving octave samplers in original-index order. */
            ImprovedNoise[] activeOctaves,
            /**
             * Per-active-octave input frequency, baked as
             * {@code lowestFreqInputFactor * 2^originalIdx}. The codegen emits this as
             * an {@code LDC} immediately followed by {@code DMUL} on each spilled
             * coordinate slot.
             */
            double[] inputFactors,
            /**
             * Per-active-octave output factor, baked as
             * {@code amplitudes[originalIdx] * lowestFreqValueFactor * 0.5^originalIdx}.
             * Multiplied with {@code ImprovedNoise.noise(...)} once per octave; the
             * results are summed into the per-branch accumulator.
             */
            double[] ampValueFactors,
            /**
             * Pre-scale applied to each coordinate before the octave loop runs.
             * {@code 1.0} for {@code first}, {@link NoiseSpec#INPUT_FACTOR} for
             * {@code second}. The codegen elides the multiply when this is exactly
             * {@code 1.0} (which keeps {@code first}'s loop tight).
             */
            double inputCoordScale
    ) {
        /** {@code true} when there are no live octaves at all (all-zero amplitudes). */
        public boolean isEmpty() {
            return activeOctaves.length == 0;
        }
    }

    /** Total active octaves across both branches — what the codegen unrolls. */
    public int totalActiveOctaves() {
        return first.activeOctaves.length + second.activeOctaves.length;
    }
}
