package dev.sixik.generator_accelerator.common.density.compiler.compiler.pipeline;

import com.google.common.collect.MapMaker;
import dev.sixik.generator_accelerator.common.density.compiler.compiler.Compiler;
import dev.sixik.generator_accelerator.common.density.compiler.compiler.MarkerRewriter;
import dev.sixik.generator_accelerator.common.density.compiler.compiler.codegen.CompiledDensityFunction;
import net.minecraft.world.level.levelgen.DensityFunction;
import net.minecraft.world.level.levelgen.DensityFunctions;

import java.util.concurrent.ConcurrentMap;

/**
 * The single {@link DensityFunction.Visitor} we install everywhere. It is the
 * <em>entry point</em> for compilation, not a tree walker: callers pass us a root they
 * want compiled and we return either the same instance (if it can't be compiled), a
 * {@link CompiledDensityFunction}, or — for markers — a fresh
 * {@link DensityFunctions.Marker} whose inner subtree has been replaced with the
 * compiled version.
 *
 * <p><strong>We never recurse via {@link DensityFunction#mapAll mapAll}.</strong>
 * mapAll is post-order: it would invoke {@link #apply} on every internal node, and
 * each invocation compiles a fresh hidden class that just delegates back to its
 * already-compiled child via {@code INVOKEINTERFACE}. That blew up to ~37k generated
 * classes for a vanilla Overworld router (35 source roots) before this rewrite.
 * Instead, the {@link Compiler} walks the original (unrewritten) source tree itself
 * inside {@link dev.sixik.generator_accelerator.common.density.compiler.compiler.ir.IRBuilder},
 * inlining every recognised node into the same generated bytecode. We only get a fresh
 * hidden class per <em>marker boundary</em> (which has to stay separate so
 * {@code NoiseChunk} can swap it with a cell cache).
 *
 * <p>The cache is identity-keyed by source DF: same source instance ↔ same compiled
 * output. {@link MapMaker#weakKeys()} lets the source GC out across {@code /reload};
 * {@link MapMaker#weakValues()} lets the hidden class drop out of metaspace once
 * nothing references the compiled instance. We cache markers by source-marker identity
 * too so that repeated visits hand back the <em>same</em> repackaged Marker — that's
 * what {@link net.minecraft.world.level.levelgen.NoiseChunk}'s
 * {@code wrapped} HashMap dedup relies on (it uses Marker record equality, which is
 * structural over {@code (type, wrapped)} — sharing the inner instance keeps
 * deduplication tight).
 */
public final class CompilingVisitor implements DensityFunction.Visitor {

    private static final CompilingVisitor INSTANCE = new CompilingVisitor();

    /**
     * Identity-keyed compile cache. Use {@link MapMaker#weakKeys()} so the source
     * DensityFunction can be GC'd; {@link MapMaker#weakValues()} so the compiled hidden
     * class can drop out of metaspace once nobody references it.
     */
    private final ConcurrentMap<DensityFunction, DensityFunction> cache =
            new MapMaker().weakKeys().weakValues().concurrencyLevel(4).makeMap();

    private CompilingVisitor() {}

    public static CompilingVisitor global() {
        return INSTANCE;
    }

    @Override
    public DensityFunction apply(DensityFunction df) {
        // Already-compiled, identity-significant sentinels and HolderHolder shells
        // pass through unchanged. NoiseChunk identity-checks BlendAlpha/BlendOffset/
        // BeardifierMarker; if we wrap them in a CompiledDF the identity comparison
        // breaks and the chunk can't install its blending hooks, which makes the world
        // generate as if Blender was disabled (no smooth biome borders, abrupt cliffs).
        if (df instanceof CompiledDensityFunction
                || df instanceof DensityFunctions.BlendAlpha
                || df instanceof DensityFunctions.BlendOffset
                || df == DensityFunctions.BeardifierMarker.INSTANCE
                || df instanceof DensityFunctions.Constant) {
            return df;
        }
        // Lazy NoiseRouter field wrapper: compile the wired tree, not the shell.
        if (df instanceof OnDemandCompilingDensityFunction odf) {
            return apply(odf.wired());
        }
        // HolderHolder is a thin pointer to a registry value; peel it eagerly so we
        // compile the underlying DF once and share it across every router that points at
        // the same density_function entry. NoiseChunk.wrap also peels HolderHolder, so
        // returning the inner directly matches vanilla semantics.
        if (df instanceof DensityFunctions.HolderHolder hh) {
            return apply(hh.function().value());
        }
        // Markers are a contract with NoiseChunk: the chunk swaps them with cell caches
        // (Cache2D / FlatCache / NoiseInterpolator / CacheOnce / CacheAllInCell). We have
        // to preserve the marker boundary verbatim, but the inner subtree is fair game
        // for compilation. Cache the WHOLE marker by source identity so repeat visits
        // return the same repackaged Marker instance — Marker is a record (structural
        // equality), so the wrapped() HashMap in NoiseChunk dedups it correctly only
        // when the inner CompiledDF is shared between markers, which our identity-keyed
        // cache guarantees.
        if (df instanceof DensityFunctions.MarkerOrMarked marker) {
            DensityFunction cached = cache.get(df);
            if (cached != null) return cached;
            DensityFunction inner = marker.wrapped();
            DensityFunction compiledInner = apply(inner);
            DensityFunction result = (compiledInner == inner)
                    ? df
                    : MarkerRewriter.rebuild(marker.type(), compiledInner);
            DensityFunction prior = cache.putIfAbsent(df, result);
            return prior != null ? prior : result;
        }

        // Non-marker root compile. We deliberately use get + putIfAbsent rather than
        // computeIfAbsent because Compiler::compile recursively invokes apply() on the
        // tree it's compiling (when it hits a Marker, the marker's inner subtree gets
        // compiled as its own unit). Nested computeIfAbsent on different keys in
        // Guava's MapMaker concurrent map can throw or block under contention; the
        // worst case for putIfAbsent is two threads compiling the same root once and
        // discarding one result, which is acceptable for an idempotent compile.
        DensityFunction cached = cache.get(df);
        if (cached != null) return cached;
        DensityFunction compiled = Compiler.compile(df);
        DensityFunction prior = cache.putIfAbsent(df, compiled);
        return prior != null ? prior : compiled;
    }

    @Override
    public DensityFunction.NoiseHolder visitNoise(DensityFunction.NoiseHolder holder) {
        return holder;
    }

    /** For tests / dump command — returns approximate cache size (may be stale due to GC). */
    public int cacheSize() {
        return cache.size();
    }
}
