modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Unlicense"

[[mods]]
modId = "generator_accelerator"
version = "${version}"
displayName = "Generator Accelerator"
authors = "Sixik"
description = '''

'''
#logoFile = ""

[[dependencies.generator_accelerator]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.generator_accelerator]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "generator_accelerator.mixins.json"

[[mixins]]
config = "generator_accelerator_density.mixins.json"

[[mixins]]
config = "generator_accelerator_benchmark.mixins.json"

[[mixins]]
config = "generator_accelerator_biome.mixins.json"

[[mixins]]
config = "generator_accelerator_blender.mixins.json"

[[mixins]]
config = "generator_accelerator_noise.mixins.json"

[[mixins]]
config = "generator_accelerator_noise_native.mixins.json"

[[mixins]]
config = "generator_accelerator_aquifer.mixins.json"

[[mixins]]
config = "generator_accelerator_heightmap.mixins.json"

[[mixins]]
config = "generator_accelerator_beardifier.mixins.json"

[[mixins]]
config = "generator_accelerator_surface.mixins.json"

[[mixins]]
config = "generator_accelerator_structures.mixins.json"

[[mixins]]
config = "generator_accelerator_features.mixins.json"


[[accessTransformers]]
file="META-INF/accesstransformer.cfg"