package dev.sixik.generator_accelerator.common.density.compiler.compiler.runtime;

import dev.sixik.generator_accelerator.common.density.compiler.mixin.noise.ImprovedNoiseAccessor;
import net.minecraft.util.Mth;
import net.minecraft.world.level.levelgen.synth.ImprovedNoise;

/**
 * Java-only fused noise kernels used by generated density-function bytecode.
 *
 * <p>The generated class snapshots the private {@link ImprovedNoise} permutation table and
 * offsets once in its constructor, then calls these monomorphic static kernels from the hot
 * path. That removes per-octave {@code Runtime.wrapAxis} calls and virtual
 * {@code ImprovedNoise.noise(...)} dispatch from generated bytecode without JNI.
 */
public final class DfcJavaNoiseKernel {
    private static final double WRAP = 33_554_432.0D;

    private static final double[] FLAT_SIMPLEX_GRAD = new double[] {
            1, 1, 0, 0, -1, 1, 0, 0, 1, -1, 0, 0, -1, -1, 0, 0,
            1, 0, 1, 0, -1, 0, 1, 0, 1, 0, -1, 0, -1, 0, -1, 0,
            0, 1, 1, 0, 0, -1, 1, 0, 0, 1, -1, 0, 0, -1, -1, 0,
            1, 1, 0, 0, 0, -1, 1, 0, -1, 1, 0, 0, 0, -1, -1, 0
    };

    private DfcJavaNoiseKernel() {
    }

    public static final class NormalKernel {
        final double valueFactor;
        final Branch first;
        final Branch second;

        private NormalKernel(double valueFactor, Branch first, Branch second) {
            this.valueFactor = valueFactor;
            this.first = first;
            this.second = second;
        }
    }

    public static final class BlendedKernel {
        final double xzMultiplier;
        final double yMultiplier;
        final double xzFactor;
        final double yFactor;
        final double smearScaleMultiplier;
        final BlendedBranch main;
        final BlendedBranch minLimit;
        final BlendedBranch maxLimit;

        private BlendedKernel(
                double xzMultiplier,
                double yMultiplier,
                double xzFactor,
                double yFactor,
                double smearScaleMultiplier,
                BlendedBranch main,
                BlendedBranch minLimit,
                BlendedBranch maxLimit
        ) {
            this.xzMultiplier = xzMultiplier;
            this.yMultiplier = yMultiplier;
            this.xzFactor = xzFactor;
            this.yFactor = yFactor;
            this.smearScaleMultiplier = smearScaleMultiplier;
            this.main = main;
            this.minLimit = minLimit;
            this.maxLimit = maxLimit;
        }
    }

    private static class Octaves {
        final byte[][] permutations;
        final double[] xo;
        final double[] yo;
        final double[] zo;

        Octaves(byte[][] permutations, double[] xo, double[] yo, double[] zo) {
            this.permutations = permutations;
            this.xo = xo;
            this.yo = yo;
            this.zo = zo;
        }
    }

    private static final class Branch extends Octaves {
        final double inputCoordScale;
        final double[] inputFactors;
        final double[] ampValueFactors;

        Branch(
                byte[][] permutations,
                double[] xo,
                double[] yo,
                double[] zo,
                double inputCoordScale,
                double[] inputFactors,
                double[] ampValueFactors
        ) {
            super(permutations, xo, yo, zo);
            this.inputCoordScale = inputCoordScale;
            this.inputFactors = inputFactors;
            this.ampValueFactors = ampValueFactors;
        }
    }

    private static final class BlendedBranch extends Octaves {
        final double[] factors;

        BlendedBranch(byte[][] permutations, double[] xo, double[] yo, double[] zo, double[] factors) {
            super(permutations, xo, yo, zo);
            this.factors = factors;
        }
    }

    public static NormalKernel normal(
            Object[] payload,
            int base,
            double valueFactor,
            double firstInputCoordScale,
            double[] firstInputFactors,
            double[] firstAmpValueFactors,
            double secondInputCoordScale,
            double[] secondInputFactors,
            double[] secondAmpValueFactors
    ) {
        int firstCount = firstInputFactors.length;
        Branch first = branch(
                payload,
                base,
                firstCount,
                firstInputCoordScale,
                firstInputFactors,
                firstAmpValueFactors
        );
        Branch second = branch(
                payload,
                base + firstCount,
                secondInputFactors.length,
                secondInputCoordScale,
                secondInputFactors,
                secondAmpValueFactors
        );
        return new NormalKernel(valueFactor, first, second);
    }

    public static BlendedKernel blended(
            Object[] payload,
            int base,
            double xzMultiplier,
            double yMultiplier,
            double xzFactor,
            double yFactor,
            double smearScaleMultiplier
    ) {
        return new BlendedKernel(
                xzMultiplier,
                yMultiplier,
                xzFactor,
                yFactor,
                smearScaleMultiplier,
                blendedBranch(payload, base, 8),
                blendedBranch(payload, base + 8, 16),
                blendedBranch(payload, base + 24, 16)
        );
    }

    public static double sampleNormal(NormalKernel kernel, double x, double y, double z) {
        return (sampleBranch(kernel.first, x, y, z) + sampleBranch(kernel.second, x, y, z))
                * kernel.valueFactor;
    }

    public static double sampleBlended(BlendedKernel kernel, int blockX, int blockY, int blockZ) {
        double scaledX = (double) blockX * kernel.xzMultiplier;
        double scaledY = (double) blockY * kernel.yMultiplier;
        double scaledZ = (double) blockZ * kernel.xzMultiplier;

        double mainX = scaledX / kernel.xzFactor;
        double mainY = scaledY / kernel.yFactor;
        double mainZ = scaledZ / kernel.xzFactor;

        double limitYScale = kernel.yMultiplier * kernel.smearScaleMultiplier;
        double mainYScale = limitYScale / kernel.yFactor;

        double main = 0.0D;
        BlendedBranch mainBranch = kernel.main;
        for (int i = 0; i < mainBranch.factors.length; i++) {
            double factor = mainBranch.factors[i];
            main += sampleImproved(
                    mainBranch.permutations[i],
                    mainBranch.xo[i],
                    mainBranch.yo[i],
                    mainBranch.zo[i],
                    wrapAxis(mainX * factor),
                    wrapAxis(mainY * factor),
                    wrapAxis(mainZ * factor),
                    mainYScale * factor,
                    mainY * factor
            ) / factor;
        }

        double blend = (main / 10.0D + 1.0D) * 0.5D;
        double min = 0.0D;
        double max = 0.0D;

        if (blend < 1.0D) {
            min = sampleLimitBranch(kernel.minLimit, scaledX, scaledY, scaledZ, limitYScale);
        }
        if (blend > 0.0D) {
            max = sampleLimitBranch(kernel.maxLimit, scaledX, scaledY, scaledZ, limitYScale);
        }

        return Mth.clampedLerp(min / 512.0D, max / 512.0D, blend) / 128.0D;
    }

    public static double wrapAxis(double value) {
        double scaled = value / WRAP + 0.5D;
        long truncated = (long) scaled;
        long floored = scaled < (double) truncated ? truncated - 1L : truncated;
        return value - (double) floored * WRAP;
    }

    private static double sampleLimitBranch(
            BlendedBranch branch,
            double x,
            double y,
            double z,
            double yScale
    ) {
        double sum = 0.0D;
        for (int i = 0; i < branch.factors.length; i++) {
            double factor = branch.factors[i];
            sum += sampleImproved(
                    branch.permutations[i],
                    branch.xo[i],
                    branch.yo[i],
                    branch.zo[i],
                    wrapAxis(x * factor),
                    wrapAxis(y * factor),
                    wrapAxis(z * factor),
                    yScale * factor,
                    y * factor
            ) / factor;
        }
        return sum;
    }

    private static double sampleBranch(Branch branch, double x, double y, double z) {
        if (branch.inputFactors.length == 0) {
            return 0.0D;
        }
        double sx = x;
        double sy = y;
        double sz = z;
        if (Double.compare(branch.inputCoordScale, 1.0D) != 0) {
            sx *= branch.inputCoordScale;
            sy *= branch.inputCoordScale;
            sz *= branch.inputCoordScale;
        }
        double sum = 0.0D;
        for (int i = 0; i < branch.inputFactors.length; i++) {
            double factor = branch.inputFactors[i];
            sum += sampleImproved(
                    branch.permutations[i],
                    branch.xo[i],
                    branch.yo[i],
                    branch.zo[i],
                    wrapAxis(sx * factor),
                    wrapAxis(sy * factor),
                    wrapAxis(sz * factor),
                    0.0D,
                    0.0D
            ) * branch.ampValueFactors[i];
        }
        return sum;
    }

    private static Branch branch(
            Object[] payload,
            int base,
            int count,
            double inputCoordScale,
            double[] inputFactors,
            double[] ampValueFactors
    ) {
        Octaves octaves = snapshot(payload, base, count);
        return new Branch(
                octaves.permutations,
                octaves.xo,
                octaves.yo,
                octaves.zo,
                inputCoordScale,
                inputFactors,
                ampValueFactors
        );
    }

    private static BlendedBranch blendedBranch(Object[] payload, int base, int count) {
        int active = 0;
        for (int i = 0; i < count; i++) {
            if (payload[base + i] != null) {
                active++;
            }
        }

        byte[][] permutations = new byte[active][];
        double[] xo = new double[active];
        double[] yo = new double[active];
        double[] zo = new double[active];
        double[] factors = new double[active];
        int out = 0;
        for (int i = 0; i < count; i++) {
            Object octave = payload[base + i];
            if (octave == null) {
                continue;
            }
            ImprovedNoiseAccessor accessor = (ImprovedNoiseAccessor) octave;
            permutations[out] = accessor.dfc$getPermutation();
            xo[out] = accessor.dfc$getXo();
            yo[out] = accessor.dfc$getYo();
            zo[out] = accessor.dfc$getZo();
            factors[out] = 1.0D / (double) (1L << i);
            out++;
        }
        return new BlendedBranch(permutations, xo, yo, zo, factors);
    }

    private static Octaves snapshot(Object[] payload, int base, int count) {
        byte[][] permutations = new byte[count][];
        double[] xo = new double[count];
        double[] yo = new double[count];
        double[] zo = new double[count];
        for (int i = 0; i < count; i++) {
            ImprovedNoiseAccessor accessor = (ImprovedNoiseAccessor) payload[base + i];
            permutations[i] = accessor.dfc$getPermutation();
            xo[i] = accessor.dfc$getXo();
            yo[i] = accessor.dfc$getYo();
            zo[i] = accessor.dfc$getZo();
        }
        return new Octaves(permutations, xo, yo, zo);
    }

    private static double sampleImproved(
            byte[] p,
            double xo,
            double yo,
            double zo,
            double x,
            double y,
            double z,
            double yScale,
            double yMax
    ) {
        double inputX = x + xo;
        double inputY = y + yo;
        double inputZ = z + zo;

        int gridX = fastFloor(inputX);
        int gridY = fastFloor(inputY);
        int gridZ = fastFloor(inputZ);

        double deltaX = inputX - gridX;
        double deltaY = inputY - gridY;
        double deltaZ = inputZ - gridZ;

        double weirdDeltaY;
        if (yScale != 0.0D) {
            double range = yMax >= 0.0D && yMax < deltaY ? yMax : deltaY;
            double scaled = range / yScale + 1.0E-7D;
            int scaledFloor = fastFloor(scaled);
            weirdDeltaY = deltaY - (double) scaledFloor * yScale;
        } else {
            weirdDeltaY = deltaY;
        }

        return sampleAndLerp(p, gridX, gridY, gridZ, deltaX, weirdDeltaY, deltaZ, deltaY);
    }

    private static int fastFloor(double value) {
        int truncated = (int) value;
        return value < (double) truncated ? truncated - 1 : truncated;
    }

    private static double sampleAndLerp(
            byte[] p,
            int gridX,
            int gridY,
            int gridZ,
            double x,
            double wy,
            double z,
            double y
    ) {
        double[] grads = FLAT_SIMPLEX_GRAD;

        int x0 = gridX & 0xFF;
        int y0 = gridY & 0xFF;
        int z0 = gridZ & 0xFF;

        int a = (p[x0] & 0xFF) + y0;
        int aa = (p[a & 0xFF] & 0xFF) + z0;
        int ab = (p[(a + 1) & 0xFF] & 0xFF) + z0;

        int b = (p[(x0 + 1) & 0xFF] & 0xFF) + y0;
        int ba = (p[b & 0xFF] & 0xFF) + z0;
        int bb = (p[(b + 1) & 0xFF] & 0xFF) + z0;

        int gi000 = (p[aa & 0xFF] & 15) << 2;
        int gi001 = (p[(aa + 1) & 0xFF] & 15) << 2;
        int gi010 = (p[ab & 0xFF] & 15) << 2;
        int gi011 = (p[(ab + 1) & 0xFF] & 15) << 2;
        int gi100 = (p[ba & 0xFF] & 15) << 2;
        int gi101 = (p[(ba + 1) & 0xFF] & 15) << 2;
        int gi110 = (p[bb & 0xFF] & 15) << 2;
        int gi111 = (p[(bb + 1) & 0xFF] & 15) << 2;

        double x1 = x - 1.0D;
        double wy1 = wy - 1.0D;
        double z1 = z - 1.0D;

        double n000 = grads[gi000] * x + grads[gi000 | 1] * wy + grads[gi000 | 2] * z;
        double n100 = grads[gi100] * x1 + grads[gi100 | 1] * wy + grads[gi100 | 2] * z;
        double n001 = grads[gi001] * x + grads[gi001 | 1] * wy + grads[gi001 | 2] * z1;
        double n101 = grads[gi101] * x1 + grads[gi101 | 1] * wy + grads[gi101 | 2] * z1;
        double n011 = grads[gi011] * x + grads[gi011 | 1] * wy1 + grads[gi011 | 2] * z1;
        double n111 = grads[gi111] * x1 + grads[gi111 | 1] * wy1 + grads[gi111 | 2] * z1;
        double n010 = grads[gi010] * x + grads[gi010 | 1] * wy1 + grads[gi010 | 2] * z;
        double n110 = grads[gi110] * x1 + grads[gi110 | 1] * wy1 + grads[gi110 | 2] * z;

        double u = x * x * x * (x * (x * 6.0D - 15.0D) + 10.0D);
        double v = y * y * y * (y * (y * 6.0D - 15.0D) + 10.0D);
        double w = z * z * z * (z * (z * 6.0D - 15.0D) + 10.0D);

        double lerpX1 = n000 + u * (n100 - n000);
        double lerpX2 = n010 + u * (n110 - n010);
        double lerpX3 = n001 + u * (n101 - n001);
        double lerpX4 = n011 + u * (n111 - n011);

        double lerpY1 = lerpX1 + v * (lerpX2 - lerpX1);
        double lerpY2 = lerpX3 + v * (lerpX4 - lerpX3);

        return lerpY1 + w * (lerpY2 - lerpY1);
    }
}
