package dev.sixik.generator_accelerator.common.density.compiler.compiler.runtime;

/**
 * Tiny static helpers called from generated bytecode. Kept in their own class so the
 * codegen can refer to them through a stable internal name without leaking the rest of
 * the compiler implementation onto the generated method's call graph (which would push
 * past HotSpot's inlining budget for very large IR trees).
 *
 * <p>Each helper here is short and pure — HotSpot will trivially inline them at the call
 * site once the generated method itself crosses the inlining threshold.
 */
public final class Runtime {
    private Runtime() {}

    /** {@code DensityFunctions.Mapped.Type.SQUEEZE}. */
    public static double squeeze(double x) {
        double c = x < -1.0 ? -1.0 : (x > 1.0 ? 1.0 : x);
        return c / 2.0 - c * c * c / 24.0;
    }

    /**
     * {@code WeirdScaledSampler}'s rarity mapping. {@code ordinal} is the
     * {@code DensityFunctions.WeirdScaledSampler.RarityValueMapper} ordinal
     * (0 = TYPE1 / 3D, 1 = TYPE2 / 2D). Reimplemented here because the vanilla
     * {@code QuantizedSpaghettiRarity} class is package-private — duplicating these tiny
     * tables avoids depending on access transformers.
     */
    public static double weirdRarity(double v, int ordinal) {
        return ordinal == 0 ? rarity3D(v) : rarity2D(v);
    }

    private static double rarity3D(double p) {
        if (p < -0.5) return 0.75;
        if (p < 0.0)  return 1.0;
        return p < 0.5 ? 1.5 : 2.0;
    }

    private static double rarity2D(double p) {
        if (p < -0.75) return 0.5;
        if (p < -0.5)  return 0.75;
        if (p <  0.5)  return 1.0;
        return p < 0.75 ? 2.0 : 3.0;
    }

    /**
     * Mirror of {@link net.minecraft.world.level.levelgen.synth.PerlinNoise#wrap}
     * inlined into the unrolled per-octave bytecode. Vanilla {@code PerlinNoise} uses
     * {@code Mth.lfloor(value / 33554432.0 + 0.5)} to floor the quotient before
     * subtracting; we reproduce {@code Mth.lfloor} bit-for-bit (truncating-cast then
     * decrement when the original value sits below the truncated long) so the wrap
     * result is identical to what vanilla's evaluator computes.
     *
     * <p>The constant {@code 33554432.0} is {@code 2^25}; the divisor / multiplier
     * pair caps the wrapped magnitude at {@code 2^24}, well within the precision
     * range where ImprovedNoise's lookup tables behave correctly.
     */
    public static double wrapAxis(double v) {
        double scaled = v / 33554432.0 + 0.5;
        long truncated = (long) scaled;
        long floored = scaled < (double) truncated ? truncated - 1L : truncated;
        return v - (double) floored * 33554432.0;
    }
}

