package dev.sixik.generator_accelerator.common.density.compiler.cache;

import net.minecraft.world.level.levelgen.DensityFunction;

import java.util.concurrent.atomic.LongAdder;

/**
 * Optional fast path for {@code compute} on chunk cache wrappers, called from
 * generated bytecode (see {@code Codegen#emitInvoke}).
 */
public final class DfcCacheFastPath {

    /**
     * Sentinel for "use slow {@link DensityFunction#compute}" — same trick as a miss bit pattern.
     */
    public static final long MISS_BITS = 0x7ff8000000000001L; // non-canonical quiet NaN

    public static final double CACHE_MISS = Double.longBitsToDouble(MISS_BITS);

    private static final LongAdder ELIGIBLE_CALLS = new LongAdder();
    private static final LongAdder HITS = new LongAdder();
    private static final LongAdder MISSES = new LongAdder();
    private static final LongAdder DISABLED_FALLBACKS = new LongAdder();
    private static final LongAdder NON_ACCESS_FALLBACKS = new LongAdder();

    private DfcCacheFastPath() {}

    public record Stats(long eligibleCalls, long hits, long misses,
                        long disabledFallbacks, long nonAccessFallbacks) {}

    public static Stats snapshotStats() {
        return new Stats(ELIGIBLE_CALLS.sum(), HITS.sum(), MISSES.sum(),
                DISABLED_FALLBACKS.sum(), NON_ACCESS_FALLBACKS.sum());
    }

    public static void resetStats() {
        ELIGIBLE_CALLS.reset();
        HITS.reset();
        MISSES.reset();
        DISABLED_FALLBACKS.reset();
        NON_ACCESS_FALLBACKS.reset();
    }

    public static double tryWrapperDirectRead(DensityFunction extern, DensityFunction.FunctionContext context) {
        if (extern instanceof DfcCellCacheAccess acc) {
            ELIGIBLE_CALLS.increment();
            double v = acc.dfc$tryDirectRead(context);
            if (Double.doubleToRawLongBits(v) != MISS_BITS) {
                HITS.increment();
            } else {
                MISSES.increment();
            }
            return v;
        }
        NON_ACCESS_FALLBACKS.increment();
        return CACHE_MISS;
    }

    /**
     * Marker call sites flagged at compile time for NoiseChunk cache wrappers: try
     * {@link DfcCellCacheAccess#dfc$tryDirectRead} before {@link DensityFunction#compute}.
     */
    public static double computeWithOptionalDirectRead(
            DensityFunction extern, DensityFunction.FunctionContext context) {
        if (extern instanceof DfcCellCacheAccess acc) {
            ELIGIBLE_CALLS.increment();
            double v = acc.dfc$tryDirectRead(context);
            if (Double.doubleToRawLongBits(v) != MISS_BITS) {
                HITS.increment();
                return v;
            }
            MISSES.increment();
        } else {
            NON_ACCESS_FALLBACKS.increment();
        }
        return extern.compute(context);
    }
}
