package dev.sixik.generator_accelerator.common.density.compiler.cache;

import dev.sixik.generator_accelerator.api.config.GAConfigHolder;
import net.minecraft.world.level.levelgen.DensityFunction;

import java.util.concurrent.atomic.LongAdder;

/**
 * Optional fast path for {@code compute} on chunk cache wrappers, called from
 * generated bytecode (see {@code Codegen#emitInvoke}).
 */
public final class DfcCacheFastPath {

    /**
     * Sentinel for "use slow {@link DensityFunction#compute}" — same trick as a miss bit pattern.
     */
    public static final long MISS_BITS = 0x7ff8000000000001L; // non-canonical quiet NaN

    public static final double CACHE_MISS = Double.longBitsToDouble(MISS_BITS);

    private static final LongAdder HITS = new LongAdder();
    private static final LongAdder MISSES = new LongAdder();
    private static final LongAdder DISABLED_FALLBACKS = new LongAdder();
    private static final LongAdder NON_ACCESS_FALLBACKS = new LongAdder();
    private static volatile boolean statsEnabled = Boolean.getBoolean("ga.dfc.cacheFastPath.stats")
            || GAConfigHolder.getConfig().dfc.cacheFastPathStats;

    private DfcCacheFastPath() {}

    public record Stats(long eligibleCalls, long hits, long misses,
                        long disabledFallbacks, long nonAccessFallbacks) {}

    public static Stats snapshotStats() {
        long hits = HITS.sum();
        long misses = MISSES.sum();
        return new Stats(hits + misses, hits, misses,
                DISABLED_FALLBACKS.sum(), NON_ACCESS_FALLBACKS.sum());
    }

    public static void setStatsEnabled(boolean enabled) {
        statsEnabled = enabled;
    }

    public static void resetStats() {
        HITS.reset();
        MISSES.reset();
        DISABLED_FALLBACKS.reset();
        NON_ACCESS_FALLBACKS.reset();
    }

    public static double tryWrapperDirectRead(DensityFunction extern, DensityFunction.FunctionContext context) {
        if (extern instanceof DfcCellCacheAccess acc) {
            double v = acc.dfc$tryDirectRead(context);
            if (statsEnabled()) {
                if (Double.doubleToRawLongBits(v) != MISS_BITS) {
                    HITS.increment();
                } else {
                    MISSES.increment();
                }
            }
            return v;
        }
        if (statsEnabled()) {
            NON_ACCESS_FALLBACKS.increment();
        }
        return CACHE_MISS;
    }

    /**
     * Typed fast path for call sites that already proved {@code extern instanceof DfcCellCacheAccess}.
     */
    public static double computeKnownAccess(
            DensityFunction extern, DfcCellCacheAccess access, DensityFunction.FunctionContext context) {
        double v = access.dfc$tryDirectRead(context);
        if (Double.doubleToRawLongBits(v) != MISS_BITS) {
            if (statsEnabled()) {
                HITS.increment();
            }
            return v;
        }
        if (statsEnabled()) {
            MISSES.increment();
        }
        return extern.compute(context);
    }

    /**
     * Typed path for cell caches whose buffer layout is keyed by NoiseChunk.arrayIndex.
     */
    public static double computeKnownArrayIndexAccess(
            DensityFunction extern, DfcCellCacheArrayIndexAccess access, DensityFunction.FunctionContext context) {
        double v = access.dfc$tryDirectReadByArrayIndex(context);
        if (Double.doubleToRawLongBits(v) != MISS_BITS) {
            if (statsEnabled()) {
                HITS.increment();
            }
            return v;
        }
        if (statsEnabled()) {
            MISSES.increment();
        }
        return extern.compute(context);
    }

    /**
     * Slow path for marker sites that were flagged optimistically but don't expose direct-read access.
     */
    public static double computeKnownNonAccess(
            DensityFunction extern, DensityFunction.FunctionContext context) {
        if (statsEnabled()) {
            NON_ACCESS_FALLBACKS.increment();
        }
        return extern.compute(context);
    }

    /**
     * Marker call sites flagged at compile time for NoiseChunk cache wrappers: try
     * {@link DfcCellCacheAccess#dfc$tryDirectRead} before {@link DensityFunction#compute}.
     */
    public static double computeWithOptionalDirectRead(
            DensityFunction extern, DensityFunction.FunctionContext context) {
        if (extern instanceof DfcCellCacheAccess acc) {
            double v = acc.dfc$tryDirectRead(context);
            if (Double.doubleToRawLongBits(v) != MISS_BITS) {
                if (statsEnabled()) {
                    HITS.increment();
                }
                return v;
            }
            if (statsEnabled()) {
                MISSES.increment();
            }
        } else {
            if (statsEnabled()) {
                NON_ACCESS_FALLBACKS.increment();
            }
        }
        return extern.compute(context);
    }


    private static boolean statsEnabled() {
        return statsEnabled;
    }
}
