package dev.sixik.generator_accelerator.common.density.compiler.compiler.codegen;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InvokeDynamicInsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Lightweight ASM summary for generated density-function classes.
 *
 * <p>The JVM verifier already checks structural validity; this helper keeps a
 * cheap, loggable size/profile guard around generated bytecode so optimizer work
 * can spot helper explosions, unusually large methods, and JNI call regressions.
 */
public final class BytecodeMetrics {
    private static final String DFC_NATIVE_BRIDGE = "dev/sixik/generator_accelerator/common/density/compiler/natives/DfcNativeBridge";

    private BytecodeMetrics() {}

    public record MethodMetrics(
            String name,
            String descriptor,
            int access,
            int maxStack,
            int maxLocals,
            int instructionCount,
            int invokeCount,
            int nativeBridgeInvokeCount) {
        public boolean isHelperLike() {
            return name.startsWith("helper_")
                    || name.startsWith("lattice_")
                    || name.startsWith("dfc$lattice");
        }

        public String displayName() {
            return name + descriptor;
        }
    }

    public record Summary(
            String className,
            int classBytes,
            int methods,
            int helperLikeMethods,
            int totalInstructions,
            int maxMethodInstructions,
            String largestMethod,
            int maxStack,
            int maxLocals,
            int invokeCount,
            int nativeBridgeInvokeCount,
            List<MethodMetrics> methodMetrics) {
        public String compact() {
            return "classBytes=%d, methods=%d, helperLike=%d, insns=%d, largest=%s:%d, "
                    + "maxStack=%d, maxLocals=%d, invokes=%d, nativeBridgeInvokes=%d"
                    .formatted(classBytes, methods, helperLikeMethods, totalInstructions,
                            largestMethod, maxMethodInstructions, maxStack, maxLocals,
                            invokeCount, nativeBridgeInvokeCount);
        }
    }

    public static Summary analyze(byte[] bytecode) {
        if (bytecode == null || bytecode.length == 0) {
            return new Summary("<empty>", 0, 0, 0, 0, 0, "<none>", 0, 0, 0, 0, List.of());
        }
        ClassNode cn = new ClassNode();
        new ClassReader(bytecode).accept(cn, ClassReader.SKIP_DEBUG);

        List<MethodMetrics> methods = new ArrayList<>(cn.methods.size());
        int helperLike = 0;
        int totalInstructions = 0;
        int maxMethodInstructions = 0;
        String largestMethod = "<none>";
        int maxStack = 0;
        int maxLocals = 0;
        int invokeCount = 0;
        int nativeBridgeInvokeCount = 0;

        for (MethodNode mn : cn.methods) {
            MethodMetrics mm = analyzeMethod(mn);
            methods.add(mm);
            if (mm.isHelperLike()) helperLike++;
            totalInstructions += mm.instructionCount();
            if (mm.instructionCount() > maxMethodInstructions) {
                maxMethodInstructions = mm.instructionCount();
                largestMethod = mm.displayName();
            }
            maxStack = Math.max(maxStack, mm.maxStack());
            maxLocals = Math.max(maxLocals, mm.maxLocals());
            invokeCount += mm.invokeCount();
            nativeBridgeInvokeCount += mm.nativeBridgeInvokeCount();
        }

        methods.sort(Comparator
                .comparingInt(MethodMetrics::instructionCount)
                .reversed()
                .thenComparing(MethodMetrics::name));
        return new Summary(cn.name, bytecode.length, cn.methods.size(), helperLike,
                totalInstructions, maxMethodInstructions, largestMethod, maxStack, maxLocals,
                invokeCount, nativeBridgeInvokeCount, List.copyOf(methods));
    }

    private static MethodMetrics analyzeMethod(MethodNode mn) {
        int instructions = 0;
        int invokes = 0;
        int nativeBridgeInvokes = 0;
        for (AbstractInsnNode insn = mn.instructions.getFirst(); insn != null; insn = insn.getNext()) {
            if (insn.getOpcode() >= 0) {
                instructions++;
            }
            if (insn instanceof MethodInsnNode methodInsn) {
                invokes++;
                if (DFC_NATIVE_BRIDGE.equals(methodInsn.owner)) {
                    nativeBridgeInvokes++;
                }
            } else if (insn instanceof InvokeDynamicInsnNode) {
                invokes++;
            }
        }
        boolean nativeMethod = (mn.access & Opcodes.ACC_NATIVE) != 0;
        return new MethodMetrics(mn.name, mn.desc, mn.access, mn.maxStack, mn.maxLocals,
                instructions, invokes, nativeMethod ? nativeBridgeInvokes + 1 : nativeBridgeInvokes);
    }
}
