package dev.sixik.generator_accelerator.common.density.compiler.compiler.codegen;

import net.minecraft.util.KeyDispatchDataCodec;
import dev.sixik.generator_accelerator.common.density.compiler.cache.DfcCellFillAccess;
import net.minecraft.world.level.levelgen.DensityFunction;
import net.minecraft.world.level.levelgen.DensityFunctions;
import net.minecraft.world.level.levelgen.NoiseChunk;
import net.minecraft.world.level.levelgen.synth.NormalNoise;

import java.lang.invoke.CallSite;
import java.lang.invoke.ConstantCallSite;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.util.concurrent.atomic.LongAdder;

/**
 * Abstract base for every runtime-compiled DensityFunction.
 *
 * <p>Subclasses are generated via ASM as <em>hidden classes</em> rooted at this class
 * (using {@link java.lang.invoke.MethodHandles.Lookup#defineHiddenClass}). They override
 * exactly {@link #compute(DensityFunction.FunctionContext)}, {@link #fillArray(double[],
 * DensityFunction.ContextProvider)} and the bounds methods using straight-line bytecode.
 *
 * <p>The {@link #constants}, {@link #noises}, {@link #splines} and {@link #externs}
 * arrays are the generated class's "constant pool" — every reference to a non-trivial
 * value (a noise sampler, a spline coefficient block, an opaque mod-provided child
 * DensityFunction) is fetched through {@code GETFIELD} on these instance fields, indexed
 * by the slot the {@link ConstantPool} assigned during compilation.
 *
 * <p>Keeping these as <em>instance</em> fields (rather than static finals) lets
 * {@link #mapAll(DensityFunction.Visitor)} produce a fresh instance with rebound externs
 * without recompiling — the bytecode and IR live on the class, the bindings live on the
 * instance.
 */
public abstract class CompiledDensityFunction implements DensityFunction, DfcCellFillAccess {

    private static final LongAdder MAPALL_IDENTITY_NO_OPS = new LongAdder();
    private static final LongAdder MAPALL_REBINDS = new LongAdder();

    public record MapAllStats(long identityNoOps, long rebinds) {}

    public static MapAllStats snapshotMapAllStats() {
        return new MapAllStats(MAPALL_IDENTITY_NO_OPS.sum(), MAPALL_REBINDS.sum());
    }

    public static void resetMapAllStats() {
        MAPALL_IDENTITY_NO_OPS.reset();
        MAPALL_REBINDS.reset();
    }

    /** Plain double constants pulled out of the IR (literals, spline coefficients, etc.). */
    protected final double[] constants;

    /** Noise samplers captured by identity from the source DensityFunction tree. */
    protected final NormalNoise[] noises;

    /**
     * Spline coefficient blocks. Each entry is a flattened multipoint spline state
     * referenced by inlined branch sequences in the generated bytecode. May be {@code null}
     * for arithmetic-only compiled functions.
     */
    protected final Object[] splines;

    /**
     * Opaque DensityFunctions whose internals we do not (or cannot) inline:
     * mod-provided implementations, {@link net.minecraft.world.level.levelgen.DensityFunctions.Marker}
     * wrappers (preserved for {@code NoiseChunk} to swap with cell caches), Beardifier
     * placeholders, etc.
     */
    protected final DensityFunction[] externs;

    /** Cached interval-arithmetic bounds. */
    protected final double minValue;
    protected final double maxValue;

    /**
     * MethodHandles for the helper methods the {@link Codegen} extracted into
     * separate {@code helper$N} static methods on the generated class. Indexed
     * by helper id; {@code length == 0} when the function fit a single method.
     *
     * <p>Helper dispatch goes through these handles rather than {@code INVOKESTATIC}
     * because hidden classes are forbidden from referring to themselves
     * symbolically — the JVM rejects {@code defineHiddenClass} when the constant
     * pool contains a CONSTANT_Class_info referencing the hidden class's own name.
     * Holding the handles in an instance field, looked up after define via the
     * lookup returned by {@code defineHiddenClass}, sidesteps that completely
     * (handles refer to the {@link Class} object directly, no symbolic name).
     *
     * <p>Each handle has type {@code (CompiledDensityFunction, FunctionContext)D}
     * — using the supertype rather than the hidden subclass keeps the generated
     * call-site descriptors self-reference-free as well.
     */
    protected final MethodHandle[] helperHandles;

    /**
     * Opaque JNI pointers ({@code dfc-natives}): indices {@code 0 .. noiseSpecCount-1} are
     * NormalNoise stacks; following entries are blended specs. Zero means use the Java octave path.
     */
    protected final long[] nativeNoiseHandles;

    /**
     * Optional lattice-inner postfix program for native slab evaluation ({@code dfc-natives} VM);
     * {@code null} when the subgraph is unsupported or slab batching is inactive.
     */
    protected final byte[] slabInnerProgram;

    /** Constant pool for {@link #slabInnerProgram}; empty array when the program is {@code null}. */
    protected final double[] slabInnerConsts;

    /**
     * MethodHandle bound to the generated subclass's constructor, used by
     * {@link #rebind(NormalNoise[], DensityFunction[])} to allocate fresh
     * instances when {@link #mapAll(DensityFunction.Visitor)} produces remapped
     * externs (e.g. a {@code NoiseChunk} swapping an inner {@code Marker} with
     * its cell-cache wrapper).
     *
     * <p>Has the post-{@code asType} signature
     * {@code (double[], NormalNoise[], Object[], Object[], DensityFunction[],
     * double, double, MethodHandle[], long[], MethodHandle) -> CompiledDensityFunction},
     * so {@code invokeExact} just works without further boxing or casting. The
     * trailing {@code MethodHandle} arg is the constructor MH itself, threaded
     * through so the new instance can rebind again later.
     *
     * <p>Storing the MH on the instance (rather than a static field on the
     * generated class) preserves hidden-class GC: when no compiled instance
     * survives, both the MH and the generated class become reclaimable, which
     * is what we want across {@code /reload}.
     */
    protected final MethodHandle constructorMH;

    /**
     * Flat {@code Object[]} of {@link net.minecraft.world.level.levelgen.synth.ImprovedNoise}
     * references — the per-octave samplers the generated subclass populates into
     * its own typed {@code private final ImprovedNoise} fields at construction
     * time. The array is kept on the base class purely so {@link
     * #rebind(NormalNoise[], DensityFunction[])} can pass the same payload
     * through {@link #constructorMH} when allocating a remapped instance.
     *
     * <p>The layout is determined by {@link
     * dev.sixik.generator_accelerator.common.density.compiler.compiler.codegen.ConstantPool#finishNoiseOctaves()}:
     * for each interned NoiseSpec in pool order, the first branch's active
     * octaves are concatenated, then the second branch's. The codegen knows the
     * per-spec base offset and emits per-octave {@code AALOAD + CHECKCAST
     * ImprovedNoise + PUTFIELD} into its declared fields once at construction.
     *
     * <p>Empty {@code Object[0]} when no noises were inlined for this DF.
     */
    protected final Object[] noiseOctaves;

    protected CompiledDensityFunction(
            double[] constants,
            NormalNoise[] noises,
            Object[] splines,
            Object[] noiseOctaves,
            DensityFunction[] externs,
            double minValue,
            double maxValue,
            MethodHandle[] helperHandles,
            long[] nativeNoiseHandles,
            byte[] slabInnerProgram,
            double[] slabInnerConsts,
            MethodHandle constructorMH) {
        this.constants = constants;
        this.noises = noises;
        this.splines = splines;
        this.noiseOctaves = noiseOctaves;
        this.externs = externs;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.helperHandles = helperHandles;
        this.nativeNoiseHandles = nativeNoiseHandles;
        this.slabInnerProgram = slabInnerProgram;
        this.slabInnerConsts = slabInnerConsts != null ? slabInnerConsts : new double[0];
        this.constructorMH = constructorMH;
    }

    @Override
    public final double minValue() {
        return this.minValue;
    }

    @Override
    public final double maxValue() {
        return this.maxValue;
    }

    /**
     * Delegate to {@link DensityFunction.ContextProvider#fillAllDirectly}, matching
     * vanilla {@code SimpleFunction#fillArray} semantics. The provider knows the
     * iteration pattern (cell shape, prefetch strategy) and can issue {@code compute(...)}
     * in the most cache-friendly order it has — for {@code NoiseChunk} that's the
     * cell-major iteration over the chunk slice, which both fits in L1 and lets HotSpot
     * inline our generated {@code compute} into the per-cell hot loop.
     *
     * <p>Generated subclasses are free to override {@code fillArray} with a hand-rolled
     * vectorised body (see the {@code fillarray} milestone), but in practice the inlined
     * {@code compute} call HotSpot produces is already excellent.
     */
    @Override
    public void fillArray(double[] out, DensityFunction.ContextProvider provider) {
        provider.fillAllDirectly(out, this);
    }

    @Override
    public void dfc$fillCell(double[] out, NoiseChunk chunk) {
        fillArray(out, chunk);
    }

    public final boolean dfc$hasNativeSlabInnerProgram() {
        return this.slabInnerProgram != null && this.slabInnerProgram.length > 0;
    }

    /**
     * Per-instance "rebind" hook called by {@link #mapAll(DensityFunction.Visitor)}
     * when the visitor remapped at least one extern (e.g. a {@code NoiseChunk}
     * swapping an inner {@code Marker} with its cell-cache wrapper, or
     * {@code Beardifier}/{@code BlendAlpha}/{@code BlendOffset} placeholders
     * being replaced with the per-chunk implementation).
     *
     * <p>This is critical for both correctness and performance:
     * <ul>
     *   <li>Marker swaps are how {@code NoiseChunk} installs cell caches,
     *       cell-corner interpolators, 2D caches, etc. Vanilla noise routers
     *       are calibrated against the interpolator approximation, so
     *       evaluating noise per-block instead of per-cell-corner produces
     *       wildly different (mostly negative) densities — the world ends up
     *       being all lava/ocean instead of recognisable terrain.</li>
     *   <li>Inner {@code CacheOnce}/{@code FlatCache}/{@code Cache2D} cuts
     *       worldgen runtime by 1-3 orders of magnitude on typical routers.</li>
     * </ul>
     *
     * <p>Implementation: hidden classes can't emit {@code NEW SelfClass} so
     * we can't generate a typed constructor invoke in the subclass body.
     * Instead we materialise a {@link MethodHandle} bound to the subclass's
     * constructor right after {@code defineHiddenClass} returns, store it on
     * the instance (see {@link #constructorMH}), and call it via
     * {@code invokeExact} from this base-class method. The MH was
     * {@link MethodHandle#asType(java.lang.invoke.MethodType) asType}'d to
     * return {@code CompiledDensityFunction}, so the call site has no
     * self-reference either.
     */
    protected final CompiledDensityFunction rebind(NormalNoise[] visitedNoises,
                                                   DensityFunction[] visitedExterns) {
        if (constructorMH == null) {
            // Defensive: should never happen for properly-constructed compiled
            // instances. If somebody handcrafts a CompiledDensityFunction
            // without a constructor MH (e.g. a test stub) just degrade to
            // identity rebind.
            return this;
        }
        try {
            return (CompiledDensityFunction) constructorMH.invokeExact(
                    constants, visitedNoises, splines, noiseOctaves, visitedExterns,
                    minValue, maxValue, helperHandles, nativeNoiseHandles,
                    slabInnerProgram, slabInnerConsts, constructorMH);
        } catch (Throwable t) {
            throw new RuntimeException(
                    "CompiledDensityFunction.rebind failed for "
                            + this.getClass().getName(), t);
        }
    }

    /**
     * Visitor-driven extern remap, the worldgen-hot variant. The vanilla shape
     * — clone the externs array, walk each child, rebind on any change, then
     * forward to {@code visitor.apply} — is what {@code NoiseChunk} relies on
     * to install cell caches before chunk evaluation. We preserve those semantics
     * but make three changes that recover most of the {@code mapAll} time the
     * profiler showed in {@code init_biomes} and the chunk-init prelude:
     *
     * <ol>
     *   <li><b>Within-call memoization.</b> A {@link MapAllSession} wrapper is
     *       installed on the user visitor on the outermost call. Re-entrant calls
     *       (a sibling parent compiled DF reaching us through its own externs
     *       walk) detect the wrapper via {@code instanceof}, hit the per-session
     *       memo and return the same rebound instance — which is precisely what
     *       {@code NoiseChunk}'s record-equality dedup of {@code wrapped()}
     *       requires to collapse all duplicate {@code FlatCache}/{@code NoiseInterpolator}
     *       allocations into one. The same map also keys vanilla subgraph roots so
     *       shared {@code BlendDensity} / router tails are not remapped once per
     *       extern reference.</li>
     *   <li><b>Marker-extern reuse.</b> Vanilla {@link DensityFunctions.MarkerOrMarked#mapAll}
     *       always allocates {@code new Marker(type, wrapped.mapAll(visitor))},
     *       even when the inner result is reference-identical. We bypass that by
     *       handling marker externs directly in {@link #mapExtern}: when
     *       {@code inner.mapAll} returns the same instance, we forward the
     *       <em>original</em> marker to {@code visitor.apply}, not a freshly
     *       allocated one. Same identity → {@code wrap}'s {@code computeIfAbsent}
     *       hits a single cache wrapper.</li>
     *   <li><b>Lazy externs clone.</b> We only allocate a new
     *       {@code DensityFunction[]} when at least one extern actually changed,
     *       skipping the per-call array allocation that the previous unconditional
     *       {@code new DensityFunction[length]} produced.</li>
     * </ol>
     *
     * <p>The noise array is not currently rebuilt through {@link DensityFunction.Visitor#visitNoise}
     * — {@code CompilingVisitor} passes through {@code visitNoise} unchanged and
     * noise samplers are captured by identity at compile time. Mods that override
     * {@code visitNoise} should remap at the source DensityFunction layer, before
     * the compiler captures references.
     */
    @Override
    public DensityFunction mapAll(DensityFunction.Visitor visitor) {
        MapAllSession session = (visitor instanceof MapAllSession s)
                ? s
                : new MapAllSession(visitor);

        DensityFunction cached = session.memoGet(this);
        if (cached != null) {
            return cached;
        }

        DensityFunction result = doMapAll(session);
        session.memoPut(this, result);
        return result;
    }

    private DensityFunction doMapAll(MapAllSession session) {
        final DensityFunction[] externs = this.externs;
        DensityFunction[] mappedExterns = null; // lazy clone — only allocated on first change

        for (int i = 0; i < externs.length; i++) {
            DensityFunction src = externs[i];
            DensityFunction out = mapExtern(src, session);
            if (out != src) {
                if (mappedExterns == null) {
                    mappedExterns = externs.clone();
                }
                mappedExterns[i] = out;
            }
        }

        DensityFunction rebound;
        if (mappedExterns != null) {
            MAPALL_REBINDS.increment();
            rebound = this.rebind(this.noises, mappedExterns);
        } else {
            rebound = this;
        }
        DensityFunction result = session.apply(rebound);
        if (mappedExterns == null && result == this) {
            MAPALL_IDENTITY_NO_OPS.increment();
        }
        return result;
    }

    /**
     * Apply {@code session} (which forwards to the user visitor) to a single extern.
     * Vanilla {@code MarkerOrMarked.mapAll} is bypassed for marker externs to avoid
     * its unconditional {@code new Marker(type, ...)} allocation when the inner
     * subtree didn't change — preserving original-marker identity is what lets
     * {@code NoiseChunk::wrap}'s identity/equality-keyed dedup fire.
     */
    private static DensityFunction mapExtern(DensityFunction src, MapAllSession session) {
        DensityFunction cached = session.memoGet(src);
        if (cached != null) {
            return cached;
        }

        DensityFunction result;
        if (src instanceof DensityFunctions.MarkerOrMarked marker) {
            DensityFunction wrapped = marker.wrapped();
            DensityFunction newInner = mapExtern(wrapped, session);
            DensityFunction effective = (newInner == wrapped)
                    ? src
                    : new DensityFunctions.Marker(marker.type(), newInner);
            result = session.apply(effective);
        } else {
            result = src.mapAll(session);
        }
        session.memoPut(src, result);
        return result;
    }

    @Override
    public KeyDispatchDataCodec<? extends DensityFunction> codec() {
        // Compiled functions live only in-memory; serialising a noise router back to JSON
        // after compilation would lose information anyway. If anything tries to round-trip
        // us through codecs, fail loudly rather than corrupting data.
        throw new UnsupportedOperationException(
                "CompiledDensityFunction is not serialisable (instance class: " + this.getClass().getName() + ")");
    }

    /**
     * Bootstrap method for every {@code INVOKEDYNAMIC} site that dispatches to a
     * private static helper on the hidden class itself. Returns a
     * {@link ConstantCallSite} permanently bound to the helper named
     * {@code invokedName} with type {@code invokedType}.
     *
     * <h2>Why indy here</h2>
     *
     * <p>The legacy emission sequence
     * {@code ALOAD 0 / GETFIELD helperHandles / LDC idx / AALOAD / ALOAD 0 / ALOAD 1 /
     * INVOKEVIRTUAL MethodHandle.invokeExact} is correct but the JIT only ever sees
     * the {@code MethodHandle} as a polymorphic callee through a field load and an
     * array index — it can't constant-fold across the indirection unless C2 also
     * pulls the full object hierarchy into its inlining graph. With
     * {@code INVOKEDYNAMIC + ConstantCallSite}, the call site is treated by C2 as
     * a constant-target invocation: the indirection collapses, the helper body
     * inlines into the parent method, and the per-call cost drops to roughly the
     * cost of a direct static call (no array load, no field load, no virtual
     * dispatch through {@code invokeExact}).
     *
     * <h2>Why this lookup works for hidden classes</h2>
     *
     * <p>The {@code Lookup} the JVM hands to a bsm has the access privileges of
     * the class that declared the indy site. For our hidden classes that lookup
     * carries {@code MODULE | PRIVATE} access, including the right to find
     * private static methods on itself. We deliberately call
     * {@code lookup.findStatic(lookup.lookupClass(), invokedName, type)} so the
     * resolution does <em>not</em> have to traverse an external class loader —
     * critical for hidden classes (which aren't reachable through any class
     * loader's name table).
     *
     * <h2>Used by</h2>
     *
     * <ul>
     *   <li>{@link Codegen} for the {@code helper_<idx>} dispatch sites, with
     *       {@code invokedName = "helper_5"} etc. and
     *       {@code invokedType = (LCompiledDensityFunction;LFunctionContext;)D}.</li>
     *   <li>The cell-lattice {@code lattice_y} / {@code lattice_inner} /
     *       {@code lattice_inner_batched} helpers from the {@code fillArray} override.
     *       {@code lattice_inner} adds a {@code double} Y-slab argument;
     *       {@code lattice_inner_batched} adds {@code double[][]} native slab outputs.</li>
     * </ul>
     *
     * <h2>Fallback path</h2>
     *
     * <p>The legacy {@code helperHandles[]} array is still populated by the
     * {@code Compiler} and still emitted by {@link Codegen} when the system
     * property {@code -Ddfc.indy_helpers=false} is set. That gives us a clean
     * rollback if a JVM update produces a {@link LinkageError} on indy
     * bootstrap (extremely unlikely on Java 21+, but cheap insurance).
     */
    public static CallSite bootstrapHelper(MethodHandles.Lookup lookup,
                                           String invokedName,
                                           MethodType invokedType)
            throws ReflectiveOperationException {
        Class<?> owner = lookup.lookupClass();
        MethodHandle mh = lookup.findStatic(owner, invokedName, invokedType);
        return new ConstantCallSite(mh);
    }
}
